### ISSUE TITLE
img alt attribute not updated in the modal when using navigation arrows

### ISSUE THREAD

**Issue by szilardka** [sitelint/accessible-gallery#1]
Steps to reproduce on the [demo](https://www.sitelint.com/lab/accessible-gallery/):

1. click any of the images
2. check the alt attribute of the image in the modal with Inspector (Chrome or Safari), it will contain the correct text
3. use the navigation arrows in the modal
4. alt attribute won't be updated (however the `loadingMessage` shows the correct text)
5. clicking on any of the thumbnails in the modal won't update the alt attribute either

+1 feature request: it would be awesome to be able to display the alt text below the image, like adding a `data-alt` attribute to the `accessible_gallery_modal_inner_with_image` div so it could be displayed in an `::after` element with CSS.

<img width="1582" alt="Screenshot 2024-06-18 at 08 33 31" src="https://github.com/sitelint/accessible-gallery/assets/874085/98bf3838-ba64-4e91-a5cd-e849303561b5">

**Comment by sitelint** [comment]
@szilardka It should be fixed with the following changes https://github.com/sitelint/accessible-gallery/pull/2

As for:

> +1 feature request: it would be awesome to be able to display the alt text below the image, like adding a data-alt attribute to the accessible_gallery_modal_inner_with_image div so it could be displayed in an ::after element with CSS.

We'll look into it in a separate issue: https://github.com/sitelint/accessible-gallery/issues/3
